### ISSUE TITLE
Unable to load DLL 'yrs' 

### ISSUE THREAD

**Issue by lvlinmufeng** [y-crdt/ydotnet#102]
![image](https://github.com/user-attachments/assets/b3805a92-a838-402a-9857-7b9297c06b59)

run  demo  error

**Comment by SebastianStehle** [comment]
Have you added the native package?

**Comment by lvlinmufeng** [comment]
Direct reference to the native project, you can try

**Comment by lvlinmufeng** [comment]
sorry ,Install the package and you're good to go
