### ISSUE TITLE
Integrate new method ytransaction_alive

### ISSUE THREAD

**Issue by SebastianStehle** [y-crdt/ydotnet#63]
See

```
/// Check if current branch is still alive (returns `Y_TRUE`, otherwise `Y_FALSE`).
/// If it was deleted, this branch pointer is no longer a valid pointer and cannot be used to
/// execute any functions using it.
#[no_mangle]
pub unsafe extern "C" fn ytransaction_alive(txn: *const Transaction, branch: *mut Branch) -> u8 {
    if branch.is_null() {
        Y_FALSE
    } else {
        let txn = txn.as_ref().unwrap();
        let branch = branch.as_ref().unwrap();
        if txn.store().is_alive(&BranchPtr::from(branch)) {
            Y_TRUE
        } else {
            Y_FALSE
        }
    }
    ```

**Comment by SebastianStehle** [comment]
@LSViana Can you pull the latest version to your fork so we can create new binaries?

**Comment by SebastianStehle** [comment]
I tried to use the official repo, not your fork, but so far my build does not work and I don't know why. I added an action to patch the Cargo.toml and it does not work. But I don't know why:

``
sed: can't read yrs/yffi/Cargo.toml: No such file or directory
```

**Comment by LSViana** [comment]
@SebastianStehle I just did it, can you try again now?

**Comment by SebastianStehle** [comment]
Sorry, I tried something else. I used the original repository and then apply a patch for the small changes that we need.

But I am not so sure if this new method brings us forward in the goal to have better pointer safety, as there are a lot of uncovered methods: https://github.com/y-crdt/y-crdt/issues/347

**Comment by LSViana** [comment]
Hi, @SebastianStehle!

I couldn't join the meeting last week and I didn't follow the discussion closely so far either, but I'll try to get more details during the next meeting to see how I can help.
