### ISSUE TITLE
Update core bindings to Yrs v0.18

### ISSUE THREAD

**Issue by LSViana** [y-crdt/ydotnet#91]
With the release of [Yrs v0.18](https://github.com/y-crdt/y-crdt/releases/tag/v0.18), some core functions changed and should be updated in the library.

- [x] Replace `*_unobserve_*()` bindings with call to `yunobserve()`
  - Refers to: New Observer API [#385@y-crdt](https://github.com/y-crdt/y-crdt/pull/385)
- [x] Remove `yxmlelem()`
  - [x] Fix unit tests
- [x] Remove `yxmltext()`
  - [x] Fix unit tests
- [x] Remove `ybranch_write_transaction()`
- [x] Remove `ybranch_read_transaction()`
- [x] Create bindings for `YBranchId`:
  - [x] `ybranch_id()`
  - [x] `ybranch_get()`
  - [x] `ybranch_alive()`
  - Refers to: Logical pointers [#393@y-crdt](https://github.com/y-crdt/y-crdt/pull/393)

All items above include the bindings and unit tests.

---

Breaking changes
- Remove `Doc.XmlElement()`
  - Fix: use `Doc.XmlFragment()` for root-level types and then create an `XmlElement` inside of the `XmlFragment`.
- Remove `Doc.XmlText()`
  - Fix: use `Doc.XmlFragment()` for root-level types and then create an `XmlText` inside of the `XmlFragment`.

**Comment by LSViana** [comment]
@SebastianStehle FYI, I'll work on this.

**Comment by SebastianStehle** [comment]
Awesome. I am looking forward to the new branch pointers :)
